<a href="https://colab.research.google.com/github/Simon-creator-jara/Inteligencia_artificial/blob/main/Graficas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px

In [ ]:
data = pd.read_csv('housePrice.csv',sep=';')
data.head()

ft2  nr   price
0  2104   3  399900
1  1600   3  329900
2  2400   3  369000
3  1416   2  232000
4  3000   4  539900

In [ ]:
nd = data.shape[0]
fig =px.scatter(x=np.arange(1,nd+1), y=data['price'])
fig.show()

In [ ]:
fig =px.scatter(data,x=np.arange(1,nd+1), y='price')
fig.show()

In [ ]:
fig =px.scatter(data,x='ft2', y='price')
fig.show()

In [ ]:
fig =px.scatter(data,x='nr', y='price')
fig.show()

In [ ]:
data.insert(0,'bias',np.ones(nd))
data.head()

bias   ft2  nr   price
0   1.0  2104   3  399900
1   1.0  1600   3  329900
2   1.0  2400   3  369000
3   1.0  1416   2  232000
4   1.0  3000   4  539900

In [ ]:
data_n=data/data.max()

In [ ]:
data_n.head()

bias       ft2   nr     price
0   1.0  0.469853  0.6  0.571367
1   1.0  0.357302  0.6  0.471353
2   1.0  0.535954  0.6  0.527218
3   1.0  0.316213  0.4  0.331476
4   1.0  0.669942  0.8  0.771396

In [ ]:
data_n = data_n.to_numpy()

In [ ]:
import numpy as np
np.random.seed(1)
x = data_n[:,:3]
d = data_n[:,None,3]
nd = x.shape[0]
ne = x.shape[1]
w = np.random.rand(ne,1)
print(x)
print(d)
print(w)
y = np.zeros((nd,1))
nit = 100
ecm = np.zeros((nit,1))

[[1.         0.46985261 0.6       ]
 [1.         0.35730237 0.6       ]
 [1.         0.53595355 0.6       ]
 [1.         0.31621259 0.4       ]
 [1.         0.66994194 0.8       ]
 [1.         0.44327825 0.8       ]
 [1.         0.34256364 0.6       ]
 [1.         0.31866905 0.6       ]
 [1.         0.30817329 0.6       ]
 [1.         0.33363109 0.6       ]
 [1.         0.43322912 0.8       ]
 [1.         0.44662796 0.6       ]
 [1.         0.42206342 0.6       ]
 [1.         1.         1.        ]
 [1.         0.28316213 0.6       ]
 [1.         0.51362215 0.8       ]
 [1.         0.29477445 0.4       ]
 [1.         0.27601608 0.6       ]
 [1.         0.58262617 0.8       ]
 [1.         0.67686467 0.8       ]
 [1.         0.3945958  0.6       ]
 [1.         0.42161679 0.4       ]
 [1.         0.35819562 0.6       ]
 [1.         0.43814203 0.8       ]
 [1.         0.86869138 0.6       ]
 [1.         0.24564538 0.6       ]
 [1.         0.32559178 0.6       ]
 [1.         0.56409111 0.6 

In [ ]:
x.shape[0]

47

In [ ]:
for k in range(nd):
  a = x[k,None,:] @ w
  y[k,:]=a

In [ ]:
fig =px.line(y=[y[:,0],d[:,0]])
fig.show()

In [ ]:
print(f"Los w iniciales son: {w}")
for i in range(nit):
  for k in range(nd):
    a = x[k,None,:] @ w
    y[k,:]=a
    error = y[k,None,:] - d[k,None,:]
    w = w-0.6*error*1*x[k,None,:].T
    print(f"Los w de la repetición {i+1} en el lado {k+1} son: {w}")
    ecm[i,:] = ecm[i,None,:] + 1/(2*nd)*error**2

Se han truncado las últimas 5000 líneas del flujo de salida.
 [ 0.92691683]
 [-0.03990735]]
Los w de la repetición 65 en el lado 27 son: [[0.28735022]
 [0.9750054 ]
 [0.04871018]]
Los w de la repetición 65 en el lado 28 son: [[ 0.16946673]
 [ 0.90850837]
 [-0.02201991]]
Los w de la repetición 65 en el lado 29 son: [[0.21510983]
 [0.9309324 ]
 [0.00536595]]
Los w de la repetición 65 en el lado 30 son: [[ 0.01228216]
 [ 0.81149145]
 [-0.11633066]]
Los w de la repetición 65 en el lado 31 son: [[ 0.13283409]
 [ 0.86099905]
 [-0.06810988]]
Los w de la repetición 65 en el lado 32 son: [[ 0.09159233]
 [ 0.85178918]
 [-0.07635823]]
Los w de la repetición 65 en el lado 33 son: [[ 0.11041682]
 [ 0.86036488]
 [-0.06129864]]
Los w de la repetición 65 en el lado 34 son: [[ 0.20173248]
 [ 0.92433478]
 [-0.00650924]]
Los w de la repetición 65 en el lado 35 son: [[ 0.10461701]
 [ 0.88505919]
 [-0.08420162]]
Los w de la repetición 65 en el lado 36 son: [[ 0.11597953]
 [ 0.88870545]
 [-0.07738411]]
Los 

In [ ]:
fig =px.line(y=[y[:,0],d[:,0]])
fig.show()

In [ ]:
import plotly.graph_objects as go

In [ ]:
fig = go.Figure(
    data = [
            go.Scatter(y=ecm[:,0])
            ]
    )
fig.show()

# Clasificación

In [ ]:
datos = pd.read_csv('heart.csv')
datos.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [ ]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [ ]:
x=datos.to_numpy()

In [ ]:
x

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [ ]:
datos_n=datos/datos.max()

In [ ]:
#Otra normalización
#datos_n = (datos.iloc[:,:-1]-datos.iloc[:,:-1].mean())/datos.iloc[:,:-1].std()
datos_n.head()

age  sex        cp  trestbps      chol  fbs  restecg   thalach  exang  \
0  0.818182  1.0  1.000000     0.725  0.413121  1.0      0.0  0.742574    0.0   
1  0.480519  1.0  0.666667     0.650  0.443262  0.0      0.5  0.925743    0.0   
2  0.532468  0.0  0.333333     0.650  0.361702  0.0      0.0  0.851485    0.0   
3  0.727273  1.0  0.333333     0.600  0.418440  0.0      0.5  0.881188    0.0   
4  0.740260  0.0  0.000000     0.600  0.627660  0.0      0.5  0.806931    1.0   

    oldpeak  slope   ca      thal  target  
0  0.370968    0.0  0.0  0.333333     1.0  
1  0.564516    0.0  0.0  0.666667     1.0  
2  0.225806    1.0  0.0  0.666667     1.0  
3  0.129032    1.0  0.0  0.666667     1.0  
4  0.096774    1.0  0.0  0.666667     1.0

In [ ]:
nd=datos_n.shape[0]
datos_n.insert(0,'bias',np.ones(nd))
datos_n.head()

bias       age  sex        cp  trestbps      chol  fbs  restecg   thalach  \
0   1.0  0.818182  1.0  1.000000     0.725  0.413121  1.0      0.0  0.742574   
1   1.0  0.480519  1.0  0.666667     0.650  0.443262  0.0      0.5  0.925743   
2   1.0  0.532468  0.0  0.333333     0.650  0.361702  0.0      0.0  0.851485   
3   1.0  0.727273  1.0  0.333333     0.600  0.418440  0.0      0.5  0.881188   
4   1.0  0.740260  0.0  0.000000     0.600  0.627660  0.0      0.5  0.806931   

   exang   oldpeak  slope   ca      thal  target  
0    0.0  0.370968    0.0  0.0  0.333333     1.0  
1    0.0  0.564516    0.0  0.0  0.666667     1.0  
2    0.0  0.225806    1.0  0.0  0.666667     1.0  
3    0.0  0.129032    1.0  0.0  0.666667     1.0  
4    1.0  0.096774    1.0  0.0  0.666667     1.0

In [ ]:
x=datos_n.to_numpy()

In [ ]:
x

array([[1.        , 0.81818182, 1.        , ..., 0.        , 0.33333333,
        1.        ],
       [1.        , 0.48051948, 1.        , ..., 0.        , 0.66666667,
        1.        ],
       [1.        , 0.53246753, 0.        , ..., 0.        , 0.66666667,
        1.        ],
       ...,
       [1.        , 0.88311688, 1.        , ..., 0.5       , 1.        ,
        0.        ],
       [1.        , 0.74025974, 1.        , ..., 0.25      , 1.        ,
        0.        ],
       [1.        , 0.74025974, 0.        , ..., 0.25      , 0.66666667,
        0.        ]])

In [ ]:
x=datos_n.to_numpy()
d=datos[['target']].to_numpy()
nd = x.shape[0]
ne = x.shape[1]
w = np.random.rand(ne,1)
y = np.zeros((nd,1))
nit = 100
ecm = np.zeros((nit,1))

In [ ]:

for i in range(nit):
  for k in range(nd):
    a = x[k,None,:] @ w
    print(a)
    y[k,:]=1/(1+np.exp(-a))
    error = y[k,None,:] - d[k,None,:]
    w = w-0.3*error*y[k,None,:]*(1-y[k,None,:])*x[k,None,:].T

    ecm[i,:] = ecm[i,None,:] + 1/(2*nd)*error**2

Se han truncado las últimas 5000 líneas del flujo de salida.
[[4.54168481]]
[[3.79536595]]
[[4.45300004]]
[[5.25972154]]
[[4.66081592]]
[[4.6280722]]
[[4.6632153]]
[[3.03619421]]
[[3.7998004]]
[[4.00321733]]
[[4.85061125]]
[[4.60221536]]
[[4.02853229]]
[[4.02922544]]
[[-5.04441136]]
[[-5.19277867]]
[[-4.02911675]]
[[-4.49826247]]
[[-4.95580386]]
[[-3.66986734]]
[[-3.8564582]]
[[-3.69602021]]
[[-4.17325119]]
[[-5.11076023]]
[[-4.30327568]]
[[-4.77011136]]
[[-3.19584617]]
[[-4.42215133]]
[[-4.0704512]]
[[-4.72855751]]
[[-4.20998566]]
[[-3.12492884]]
[[-4.06180557]]
[[-4.19817341]]
[[-3.61004723]]
[[-4.57064524]]
[[-4.80524224]]
[[-3.74781161]]
[[-3.67754177]]
[[-3.83363597]]
[[-5.27951328]]
[[-4.03415254]]
[[-5.27115236]]
[[-3.54941098]]
[[-5.18187452]]
[[-3.25308032]]
[[-4.56675101]]
[[-4.86725212]]
[[-3.70523894]]
[[-3.60077651]]
[[-5.00411361]]
[[-4.4958834]]
[[-4.6516731]]
[[-4.69110025]]
[[-4.44436429]]
[[-4.85572072]]
[[-4.18279239]]
[[-4.05103038]]
[[-4.51028408]]
[[-3.95631128]]


In [ ]:
fig = go.Figure(
    data = [
            go.Scatter(y=ecm[:,0])
            ]
    )
fig.show()

In [ ]:
y_redon=np.round(y)
y_redon.T.shape
y_redon.T

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
nd_2=d.T.shape[1]
nd_2

303

In [ ]:
y_redon.T[0,1]

1.0

In [ ]:
count_0_0=0
count_1_0=0
count_0_1=0
count_1_1=0
for i in range(nd_2):
  
  if y_redon.T[0,i] == 0 and  d.T[0,i]==0:
    count_0_0 +=1
  elif y_redon.T[0,i] == 1 and  d.T[0,i]==0:
    count_1_0+=1
  elif y_redon.T[0,i] == 0 and  d.T[0,i]==1:
    count_0_1 +=1
  elif y_redon.T[0,i] == 1 and  d.T[0,i]==1:
    count_1_1 +=1

In [ ]:
print(count_0_0)

117


In [ ]:
print(count_1_0)

21


In [ ]:
print(count_0_1)

11


In [ ]:
print(count_1_1)

154


In [ ]:
matriz=pd.DataFrame({'Deseados_0':[count_0_0,count_1_0],'Deseados_1':[count_0_1,count_1_1]},index=['Salida_0','Salida_1'])

In [ ]:
matriz

Deseados_0  Deseados_1
Salida_0         138           0
Salida_1           0         165